version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: laravel-app
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
    working_dir: /var/www

  mysql:
    image: mysql:5.7
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - laravel
    depends_on:
      - app

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
